### ISSUE TITLE
undefined method 'sync!' for #<ImageUploader:xxx>

### ISSUE THREAD

**Issue by kevinansfield** [apotonick/disposable#2]
A number of my models use Carrierwave for image uploads, I've just started seeing these errors when saving an instance through an operation:

```
NoMethodError: undefined method `sync!' for #<ImageUploader:0x007f8fb9263388>
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/bundler/gems/disposable-e0c4282118d0/lib/disposable/twin/sync.rb:23:in `block (2 levels) in sync!'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/bundler/gems/disposable-e0c4282118d0/lib/disposable/twin/property_processor.rb:34:in `property!'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/bundler/gems/disposable-e0c4282118d0/lib/disposable/twin/property_processor.rb:15:in `call'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/bundler/gems/disposable-e0c4282118d0/lib/disposable/twin/sync.rb:23:in `block in sync!'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/bundler/gems/disposable-e0c4282118d0/lib/disposable/twin/representer.rb:40:in `block in each'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/bundler/gems/disposable-e0c4282118d0/lib/disposable/twin/representer.rb:34:in `each'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/bundler/gems/disposable-e0c4282118d0/lib/disposable/twin/sync.rb:20:in `sync!'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/bundler/gems/disposable-e0c4282118d0/lib/disposable/twin/sync.rb:11:in `sync_models'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/bundler/gems/disposable-e0c4282118d0/lib/disposable/twin/save.rb:5:in `save'
    /Users/kevinansfield/code/rails/competio-app/app/concepts/horse/crud.rb:44:in `block in process'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/bundler/gems/trailblazer-c077c6579a7f/lib/trailblazer/operation.rb:111:in `validate'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/bundler/gems/trailblazer-c077c6579a7f/lib/trailblazer/operation/crud.rb:43:in `validate'
    /Users/kevinansfield/code/rails/competio-app/app/concepts/horse/crud.rb:43:in `process'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/bundler/gems/trailblazer-c077c6579a7f/lib/trailblazer/operation.rb:66:in `run'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/bundler/gems/trailblazer-c077c6579a7f/lib/trailblazer/operation.rb:23:in `run'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/bundler/gems/trailblazer-c077c6579a7f/lib/trailblazer/operation/controller.rb:42:in `block in run'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/bundler/gems/trailblazer-c077c6579a7f/lib/trailblazer/operation/controller.rb:73:in `operation!'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/bundler/gems/trailblazer-c077c6579a7f/lib/trailblazer/operation/controller.rb:42:in `run'
    /Users/kevinansfield/code/rails/competio-app/app/controllers/horses_controller.rb:10:in `create'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.1/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.1/lib/abstract_controller/base.rb:198:in `process_action'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.1/lib/action_controller/metal/rendering.rb:10:in `process_action'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:92:in `_run_callbacks'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.1/lib/action_controller/metal/rescue.rb:29:in `process_action'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `block in instrument'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `instrument'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.1/lib/abstract_controller/base.rb:137:in `process'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/gems/actionview-4.2.1/lib/action_view/rendering.rb:30:in `process'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.1/lib/action_controller/test_case.rb:632:in `process'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.1/lib/action_controller/test_case.rb:65:in `process'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/gems/devise-3.5.1/lib/devise/test_helpers.rb:19:in `block in process'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/gems/devise-3.5.1/lib/devise/test_helpers.rb:72:in `catch'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/gems/devise-3.5.1/lib/devise/test_helpers.rb:72:in `_catch_warden'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/gems/devise-3.5.1/lib/devise/test_helpers.rb:19:in `process'
    /Users/kevinansfield/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.1/lib/action_controller/test_case.rb:514:in `post'
    /Users/kevinansfield/code/rails/competio-app/test/controllers/horses_controller_test.rb:70:in `block (4 levels) in <class:HorsesControllerTest>'
```

This was working last week, I'll see if I can track down when exactly it started throwing this error.

**Comment by apotonick** [comment]
I know where the "problem" is. An excerpt from your operation and the contract would help, my friend! :+1:

**Comment by kevinansfield** [comment]
app/concepts/horse/crud.rb:

```
class Horse < ActiveRecord::Base
  class Create < Trailblazer::Operation
    include CRUD
    model Horse, :create

    contract do
      include Reform::Form::ModelReflections

      def self.height_units
        %w(cms hands)
      end

      def height_units
        self.class.height_units
      end

      def self.genders
        %w(Mare Gelding Stalion)
      end

      def genders
        self.class.genders
      end

      property :name
      property :breed
      property :image
      property :gender
      property :dob
      property :height
      property :height_unit
      property :competitor

      validates :name, presence: true,
        uniqueness: { case_sensitive: false, scope: :competitor_id }
      validates :gender, presence: true, inclusion: { in: genders }
      validates :height, presence: true, numericality: true
      validates :height_unit, presence: true, inclusion: { in: height_units }
      validates :competitor, presence: true
    end

    def process(params)
      validate(params[:horse]) do |f|
        f.save
      end
    end

    def competitor
      model.competitor
    end

    private

    def setup_model!(params)
      model.competitor = Competitor.find(params[:competitor_id])
    end
  end

  class Update < Create
    action :update

    contract do
      property :competitor, writeable: false
      property :remove_image
    end

    private

    def setup_model!(params)
      if params[:competitor_id]
        competitor = Competitor.find(params[:competitor_id])
        raise ActiveRecord::RecordNotFound if model.competitor != competitor
      end
    end
  end
end
```

app/models/horse.rb:

```
class Horse < ActiveRecord::Base
  belongs_to :competitor
  mount_uploader :image, ImageUploader
end
```

**Comment by kevinansfield** [comment]
After reverting to these last known working versions it's all fine again:

disposable: https://github.com/apotonick/disposable/tree/9c40c75cda555da92124cecc022e8d40938f3a2f
reform: https://github.com/apotonick/reform/tree/d57c90cd95cdcbe88883ffb02b734847d5c36223

**Comment by kevinansfield** [comment]
The bug was fixed in https://github.com/apotonick/disposable/commit/00a158f9cd3daeb7315f59233cbf284204110d7b

For reference, I implemented CarrierWave's preview image functionality in my form by using CarrierWave's `mount_uploader` helper:

```ruby
class Horse < ActiveRecord::Base
  class Create < Trailblazer::Operation
    include CRUD
    model Horse, :create

    contract do
      extend CarrierWave::Mount
      include Reform::Form::ModelReflections

      property :image
      mount_uploader :image, ImageUploader
      
      ...
      
    end
  end
end
```
